# Portuguese (pt)
disabled = false
languageCode = "pt"
languageName = "PortuguÃªs"
weight = 8
title = "David Zhang"

[params]
displayName = "PortuguÃªs"
rtl = false
dateFormat = "2 de janeiro de 2006"
description = "DiÃ¡rio de desenvolvimento de David Zhang sobre ciÃªncia da computaÃ§Ã£o e algoritmos."
copyright = "CC BY-NC-SA 4.0"

[params.author]
name = "David (Ziyuan) Zhang"
email = "davidzhang20001112@gmail.com"
image = "img/author.png"
headline = "Engenheiro de SoftwareğŸ‘¨â€ğŸ’» @RobloxğŸš€, criando sistemas de recomendaÃ§Ã£o em tempo realğŸ“Š distribuÃ­dos, de grande escalağŸŒ e baixa latÃªnciaâš¡ para milhÃµes de usuÃ¡rios globaisğŸŒ."
links = [
    { github = "https://github.com/wacry" },
    { acm = "https://icpc.global/ICPCID/6RP5EXAXJZWB" },
    { linkedin = "https://www.linkedin.com/in/dz00/" },
    { email = "mailto:davidzhang20001112@gmail.com" },
    { ko-fi = "https://buymeacoffee.com/davidzhangu" }
    #    { facebook = "https://facebook.com/username" },
    #    { mastodon = "https://mastodon.instance/@username" },
    #    { medium = "https://medium.com/username" },
    #    { microsoft = "https://www.microsoft.com/" },
    #    { patreon = "https://www.patreon.com/username" },
    #    { pinterest = "https://pinterest.com/username" },
    #    { reddit = "https://reddit.com/user/username" },
    #    { slack = "https://workspace.url/team/userid" },
    #    { snapchat = "https://snapchat.com/add/username" },
    #    { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #    { telegram = "https://t.me/username" },
    #    { threads = "https://www.threads.net/@username" },
    #    { tiktok = "https://tiktok.com/@username" },
    #    { twitter = "https://twitter.com/username" },
    #    { x-twitter = "https://twitter.com/username" },
    #    { whatsapp = "https://wa.me/phone-number" },
    #    { youtube = "https://youtube.com/username" },
    #    { codeberg = "https://codeberg.org/username" },
]
