# Vietnamese (vi)
disabled = false
languageCode = "vi"
languageName = "Tiáº¿ng Viá»‡t"
weight = 14
title = "Blowfish"

[params]
displayName = "Tiáº¿ng Viá»‡t"
rtl = false
dateFormat = "2 thÃ¡ng 1 nÄƒm 2006"
logo = "img/logo.png"
description = "Nháº­t kÃ½ phÃ¡t triá»ƒn cá»§a David Zhang vá» khoa há»c mÃ¡y tÃ­nh vÃ  thuáº­t toÃ¡n."
copyright = "CC BY-NC-SA 4.0"

[params.author]
name = "David (Ziyuan) Zhang"
email = "davidzhang20001112@gmail.com"
image = "img/author.png"
headline = "Ká»¹ sÆ° Pháº§n má»mğŸ‘¨â€ğŸ’» @RobloxğŸš€, xÃ¢y dá»±ng há»‡ thá»‘ng Ä‘á» xuáº¥t thá»i gian thá»±cğŸ“Š phÃ¢n tÃ¡n, quy mÃ´ lá»›nğŸŒ, Ä‘á»™ trá»… tháº¥pâš¡ cho hÃ ng triá»‡u ngÆ°á»i dÃ¹ng toÃ n cáº§uğŸŒ."
links = [
    { github = "https://github.com/wacry" },
    { acm = "https://icpc.global/ICPCID/6RP5EXAXJZWB" },
    { linkedin = "https://www.linkedin.com/in/dz00/" },
    { email = "mailto:davidzhang20001112@gmail.com" },
    { ko-fi = "https://buymeacoffee.com/davidzhangu" }
    #    { facebook = "https://facebook.com/username" },
    #    { mastodon = "https://mastodon.instance/@username" },
    #    { medium = "https://medium.com/username" },
    #    { microsoft = "https://www.microsoft.com/" },
    #    { patreon = "https://www.patreon.com/username" },
    #    { pinterest = "https://pinterest.com/username" },
    #    { reddit = "https://reddit.com/user/username" },
    #    { slack = "https://workspace.url/team/userid" },
    #    { snapchat = "https://snapchat.com/add/username" },
    #    { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #    { telegram = "https://t.me/username" },
    #    { threads = "https://www.threads.net/@username" },
    #    { tiktok = "https://tiktok.com/@username" },
    #    { twitter = "https://twitter.com/username" },
    #    { x-twitter = "https://twitter.com/username" },
    #    { whatsapp = "https://wa.me/phone-number" },
    #    { youtube = "https://youtube.com/username" },
    #    { codeberg = "https://codeberg.org/username" },
]
